### ISSUE TITLE
Error occurred when initializing Rocky with invalid timeout parameter

### ISSUE THREAD

**Issue by dbukhmastov** [electricimp/Rocky#24] opened 2017-07-26 19:51 UTC
#### Scenario:
```squirrel
local app = Rocky({"timeout": "invalid"});
app.onException(function(context, ex) {
    server.log("Got exception: " + ex);
    context.send(500);
});
app.on("GET", "/test", function(context) {
    context.send(200);
}.bindenv(this));
imp.wakeup(0, function() {
    local req = http.request("GET", http.agenturl() + "/test", {}, "body");
    req.sendasync(function(res){});
}.bindenv(this));
```
#### Log:
[Agent] ERROR: bad parameters to imp.wakeup(seconds, callback[, name])
[Agent] ERROR:   from _onrequest agent_code:178
#### Tests:
This issue affects class: tests/RockyConstructor.agent.test.nut method: testRockyTimeoutOption()

**Comment by smittytone** [comment] 2019-11-05 11:43
This is a duplicate of https://github.com/electricimp/Rocky/issues/23

**Closed as completed by smittytone** 2019-11-05 11:43 UTC
